# Generated by Django 5.2.6 on 2025-10-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('anons', models.CharField(max_length=500, verbose_name='анонс')),
                ('FULL', models.TextField(verbose_name='фулл текст')),
                ('date', models.DateField(verbose_name='дата')),
            ],
        ),
    ]
