# Generated by Django 5.2.6 on 2025-11-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='FULL',
            field=models.TextField(verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(max_length=500, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
